### ISSUE TITLE
Feature request: Permanent scan service

### ISSUE THREAD

**Issue by amilopowers** [openbmap/radiocells-scanner-android#124]
Would it be possible to add an option to scan always. I mean without really running the whole app. Just in background. The openwlanmap app does that as well and I think it safes battery and like that scanners would more often work for the project. There should also be an option to start the app at boot.

**Comment by mvglasow** [comment]
See #57: I'd suggested listening to the passive location provider, and as soon as another app uses GPS, collect wifis.

**Comment by gdt** [comment]
Given #57, I suggest closing this.   I don't understand what "scan without running the whole app" means, as using location seems to big the big drain, perhaps followed by asking for cell/wifi scan info.
