### ISSUE TITLE
Rename this repo to RadioBeacon?

### ISSUE THREAD

**Issue by agilob** [openbmap/radiocells-scanner-android#152]

**Comment by gdt** [comment]
That's fine with me.   I am really unclear on how renaming impacts forks, but it seems that the transition to organization preserved history and kept forks pointed at the same repo, so it sounds like it will be reasonably smooth.

**Comment by agilob** [comment]
If you added upstream repo you will need to modify .git/config anyway to change path.

**Comment by diegocrzt** [comment]
:+1: vote for this

**Comment by mvglasow** [comment]
+1, probably the cleanest approach, now that the repo's moved from the "generic openbmap" it once was to "Radiobeacon only".

**Comment by AreYouLoco** [comment]
+1 I agree that it would be much more clean what this repo stands for

**Comment by wish7code** [comment]
Would renaming it to **radiocells-client-android** be ok for everybody?

In the long run, I'm planning to make naming more consistent, i.e. dropping Radiobeacon and openbmap as distinct names and replace it all together by Radiocells. I still have to contact our friends at F-Droid to check whether they could rename our existing apk too to avoid further confusion..

**Comment by agilob** [comment]
FDroid pull app name from .apk files, as long as application id is not changed, it's fine to change app name any time.

**Comment by gdt** [comment]
Organizing around radiocells as the main name makes sense to me.

nitpicking, -client- is funny, because there are multiple kinds of code: scanners, location provider plugins, and the website/server stuff.   So I would call the android scanner app radiocells-scanner-android and the NLP plugin radiocells-nlp-android.

**Comment by wish7code** [comment]
Makes perfect sense ;-) Repo renamed to radiocells-scanner-android/radiocells-nlp-android.
