### ISSUE TITLE
 [CM13/A6.0.1] Application crash on start to capture networks

### ISSUE THREAD

**Issue by AreYouLoco** [openbmap/radiocells-scanner-android#172]
1. What is the expected output? What do you see instead?
Expected would be preview of capturing networks. Instead I see crash notification. Application is restarting to work on capture preview screen and not capturing network, GPS signal is red.

2. What version are you using? On what operating system?
I use freshly installed RadioBeacon from F-droid repo (v0.8.18). CM13 on Elephone p9000

I tried all 'Wireless scan modes'. Same result.

I have map dowloaded and selected but no openbmap.sql database. I am downloading now I will try again with database.

Could someone help me debug this crash?

**Comment by wish7code** [comment]
Could you provide any logcats?

Also currently Radiobeacon is under heavy clean-up measures. So if you like, I could provide you with an early alpha version of next release (not yet pushed upstream)..

**Comment by AreYouLoco** [comment]
Yes please. I will try to check logcat.

**Comment by AreYouLoco** [comment]
1. I have downlaoded and selected (world) sql database and (local) map.
2. Checked GPS if works with Osmand~.[YES] Everything looks ok even if it takes time to get location without WiFi Provider.

Application crashes just after touching ⊕ (circled plus, just after clicking on old session and just after holding old session and choosing Resume.

I dont know how to use logcat properly...

**Comment by robinpaulson** [comment]
I get the same issues as AreYouLoco, I will look for a suitable log.

**Comment by AreYouLoco** [comment]
I flashed another ROM (aokp_p9000_mm_nightly_2017-04-07_ota.zip), I did full wipe and I no longer suffer from that bug. I think it might be related to dirty flashing different roms. All the people that experience this bug please, do a proper full wipe and clean install and try to run app again.
