### ISSUE TITLE
image on homepage missing

### ISSUE THREAD

**Issue by mega-stoffel** [openbmap/radiocells-scanner-android#181]
What steps will reproduce the problem?
On the homepage goto "API - Browse Data" and chose WIFI.
Enter an existing BSSID and let it show on the map.

What is the expected output? What do you see instead?
Where you should see an icon you only see "missing image".
It looks like it can't find this image:
https://www.radiocells.org/images/marker-icon.png

What version are you using? On what operating system?
Firefox on Ubuntu

Please provide any additional information below.

**Comment by wish7code** [comment]
Thanks for reporting.. 

At least the missing icon is fixed by now.. Still the subpage is ugly as hell and needs a facelift  ;-)
