### ISSUE TITLE
Warning if WIFI is de-activated

### ISSUE THREAD

**Issue by mega-stoffel** [openbmap/radiocells-scanner-android#185]
Hej - just a few days ago I was cycling through some WIFI-unknown territory and wanted to collect all the new WIFIs there. Unfortunately I had my WIFI disabled and forgot to switch it on before the tour. As a result I did not collect any WIFIs, what a pitty.

Would it be possible to generate some kind of warning, whenever I start or restart a recording session and WIFI is de-activated?

**Comment by wish7code** [comment]
Fixed in upcoming release..

Thanks for suggestion!
