### ISSUE TITLE
database excerpts on radiocells.org empty

### ISSUE THREAD

**Issue by chrisgee** [openbmap/radiocells-scanner-android#195]
What steps will reproduce the problem?
Download de.sqlite at https://cdn.radiocells.org/de.sqlite

What is the expected output? What do you see instead?
de.sqlite with cell and wifi data. de.sqlite has a size of only 1.6MB and contains no wifi data.

**Comment by wish7code** [comment]
Thanks for reporting!

Stabilizing the server still takes a couple of days, but I now updated the databases manually.
Please check and feel free to re-open in case of issues!
