### ISSUE TITLE
Errors on website

### ISSUE THREAD

**Issue by letorbi** [openbmap/radiocells-scanner-android#199]
Hej,

I just want to let you know that there seems to be a problem with the website. I know that this repo is about the Android app, but I don't know where to report else.

Every time I visit https://radiocells.org/ I get the following notification after a few seconds:

> An error occured, please reload the page

All sub-pages are not accessible at all. They are just showing the following message:

> Internal error
> Ticket issued: openbmap/93.193.141.72.2017-07-24.16-45-25.3d99a375-704a-4fdf-9132-426123895f6e

I've tried to visit the page with Firefox and Chrome on mobile and desktop. Every time with the same result. Everything worked fine when I visited the page on last Friday.

Bye
Torben

**Comment by wish7code** [comment]
Thanks for reporting! It's a backend database issue, we'll have to fix!
I'm on it.

**Comment by letorbi** [comment]
The problem seems to be fixed, so I'm closing this issue. Feel free to re-open it if needed ;)
