### ISSUE TITLE
Offline Midwest map link no good.

### ISSUE THREAD

**Issue by Locash** [openbmap/radiocells-scanner-android#202]
Downloading the offline midwest map gave a error that the link was no good. It was a google Drive link.
The other offline maps  northeast, south ,pacific for the US  all worked  and were non Google Drive links.

Thank you

**Comment by wish7code** [comment]
Good catch, thanks for reporting.. Fixed by now.

Since you're the first who asked, another question from my side:

I was wondering, whether it would make sense to split Midwest map into its single states?
Possible benefit: less space occupied on device, smaller downloads,..

Any opinions?

**Comment by Locash** [comment]
Good day! Great app by the way!

Answering your question, with the map file for the us-midwest at .6gb and the us-south at .9gb. In my opinion it would be in the best interest of the individual app user to offer the offline maps of the US broken up into states and the other countries maps the same _**if**_ the file is over 100 mb give or take.
