### ISSUE TITLE
Statistics on web site seem incorrect

### ISSUE THREAD

**Issue by mvglasow** [openbmap/radiocells-scanner-android#203]
What steps will reproduce the problem?
Browse country stats on the website (countries with updates in August)

What is the expected output? What do you see instead?
I’m currently travelling through Finland, Estonia, Latvia, Lithuania and Poland. Of these three, only Finland shows up in the statistics as having any new wifis (the number is in the neighborhood of new wifis I discovered during my stay there). The other four show no new wifis at all, although I did collect and upload some (daily since August 12).

What version are you using? On what operating system?

Please provide any additional information below.
The number of cells looks like I was the only one uploading data for these places in that time—which is certainly possible.

**Comment by wish7code** [comment]
Thanks for reporting: Fixed an hickup in the stats calculation...

**Comment by mvglasow** [comment]
Looks better now indeed. Thanks!
