### ISSUE TITLE
Certificate on radiocells.org expired

### ISSUE THREAD

**Issue by mvglasow** [openbmap/radiocells-scanner-android#210]
What steps will reproduce the problem?
Navigate to https://radiocells.org in your browser, or try to upload data with Radiobeacon.

What is the expected output? What do you see instead?
Instead of the website or a regular upload, I get an error message: the browser reports that the cert expired on Oct 20, 21:02 UTC; Radiobeacon just reports an error.

What version are you using? On what operating system?
Firefox 56.0 on Ubuntu MATE 16.04, Radiobeacon 0.8.18 on LineageOS 14.1 (Android 7.1.2)

Please provide any additional information below.
The error is caused by an expired TLS certificate.

**Comment by JonnyTech** [comment]
Is there any other way to upload my scans from radiobeacon?

**Comment by mvglasow** [comment]
None that I know of. As a hack, you could try disabling time sync with the network on your device, then manually set it to a date/time before the cert expired, then upload again. That way the device might consider the cert valid.

**Comment by wish7code** [comment]
Hey guys!

Sorry, I've been completely offline for a couple of days due to country holydays.

I just renewed the certificates.

Thanks for reporting!
