### ISSUE TITLE
Error at uploading cell Data

### ISSUE THREAD

**Issue by ctrinker2** [openbmap/radiocells-scanner-android#211]
What steps will reproduce the problem?
Always at updating cells data. 

What is the expected output? What do you see instead?
Uploading will start, but after a while ther stands:
"Exportfehler:
Versuch es zu einem späteren Zeitpunkt nochmal. Falls die Probleme weiter bestehen, schick uns eine Nachricht auf https://github.com/wish7code/openbmap /issues" 

And second error (alternating with the first error) :
A Exportfehler 

Versuch es zu einem späteren Zeitpunkt nochmal. Falls die Probleme weiter bestehen, schick uns eine Nachricht auf https://github.com/wish7code/openbmap /issues 

OK 

"Exportfehler 
Server nicht erreichbar. Entweder bist Du offline oder wir haben ein Server-Problem!" 

What version are you using? On what operating system?
Android 7.0 huawei p10lite emui 5.1

Please provide any additional information below.
Error exists since 2017-10-20 or 2017-10-21

**Comment by ctrinker2** [comment]
I'm using radio beacon 0.8.18
error while uploading anonymous aswell as uploading with my username.

**Comment by Freso** [comment]
Duplicate of https://github.com/openbmap/radiocells-scanner-android/issues/210

**Comment by wish7code** [comment]
Sorry, this was a SSL related problem with certificate renewal which is fixed by now.

If problems persists, please feel free to reopen!

**Comment by JonnyTech** [comment]
@wish7code can you please renew the certificate again

**Comment by wish7code** [comment]
@JonnyTech Thanks for reminder. Should be working again..
